version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: admin
      APP_USER: quarkus
      APP_USER_PASSWORD: quarkus123
    ports:
      - "1521:1521"

  quarkus-graphql-websocket:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.native
    container_name: quarkus-graphql-websocket
    depends_on:
      - oracle-db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus123
      QUARKUS_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      QUARKUS_JPA_HIBERNATE_DDL_AUTO: update
      QUARKUS_JPA_SHOW_SQL: "true"
      QUARKUS_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.OracleDialect

    ports:
      - "8081:8080"
