version: '3.8'
services:
  quarkus-graphql-websocket:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.native
    container_name: quarkus-graphql-websocket
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://hydrogen-database.c5cqe8wwmx8r.ap-southeast-1.rds.amazonaws.com:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_JPA_HIBERNATE_DDL_AUTO: update
      QUARKUS_JPA_SHOW_SQL: "true"
      QUARKUS_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8081:8080"
